# NB: this is only used for local development
# see Dockerfile for deployed version

db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

django:
  build: .
  command: make testserve
  ports:
    - "8000:8000"
    - "8800:8800"
  links:
    - db
  environment:
    ENV: local
    DEBUG: "True"
    DJANGO_SECRET_KEY: CHANGE_ME
    DJANGO_SETTINGS_MODULE: mtp_api.settings.docker
    DB_NAME: mtp_api
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    DB_HOST: db
    DB_PORT: 5432
